name: Kryptokrona Master Pipeline

env:
  GITHUB_REGISTRY: "ghcr.io"
  GITHUB_OWNER: "kryptokrona"
  GITHUB_DOCKER_IMAGE: "kryptokrona"

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{steps.create_release.outputs.upload_url}}
      
    
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: "Build: Windows Server 2019 MSVC"
    runs-on: windows-2019
    needs: [create-release]
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: "Install Dependencies"
        run: |
          choco install -y cmake git
          choco install -y boost-msvc-14.1
          # Additional dependencies for your project

      - name: Create Build Directory
        run: mkdir build

      - name: Build Windows Target
        run: |
          cmake -G "Visual Studio 16 2019" -A x64 -DBoost_USE_STATIC_LIBS=ON -DBoost_USE_STATIC_RUNTIME=ON ..
          MSBuild kryptokrona.sln /p:Configuration=Release /p:PlatformToolset=v141
        working-directory: build

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kryptokrona-windows-2019
          path: |
            build/Release/kryptokronad.exe
            build/Release/xkrwallet.exe
            build/Release/kryptokrona-service.exe
            build/Release/miner.exe
            build/Release/wallet-api.exe

      - name: Package Artifacts
        run: |
          powershell Compress-Archive -Path build/Release/kryptokronad.exe,build/Release/xkrwallet.exe,build/Release/kryptokrona-service.exe,build/Release/miner.exe,build/Release/wallet-api.exe -DestinationPath kryptokrona-windows-2019.zip

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: kryptokrona-windows-2019.zip
          asset_name: kryptokrona-windows-2019.zip
          asset_content_type: application/zip
